### ISSUE TITLE
issue with relative imports

### ISSUE THREAD

**Issue by adrianandreias** [public/flake8-import-order#24]
After updating to 2014-10-29 version I started getting lots of:

    I201 Missing newline before sections or imports.

For absolute imports followed by relative imports:

    from myproject.app.tests import UserFactory
    from .tests import SomeClass

I have these settings defined in tox.ini:

    import-order-style=google
    application-import-names=myproject,myproject2

Anyone else getting changed behavior with the 2014-10-29 release?

**Comment by meshy** [comment]
> Yes, but then I'll no longer have validation against the 3 PEP8 defined import groups: stdlib, 3rd party and local.

**Comment by adrianandreias** [comment]
Yeah, I'm stuck with an older version to overcome this. I still don't understand why @server and @alex are using a standard of their own. Standard that is not specified in PEP8 nor in Google standards.

**Comment by meshy** [comment]
Perhaps this could be overcome by having more fine-grained configuration options... that way, people can use their own standards by diverging from the default.

**Comment by public** [comment]
On pyca/cryptography we wanted to avoid ambiguity in the ordering so we extended it ourselves. I would like to have a more compatible mode in this though.
