### ISSUE TITLE
import posixpath

### ISSUE THREAD

**Issue by philtay** [public/flake8-import-order#28]
posixpath is not considered a standard library module

**Comment by untitaker** [comment]
How so?

    Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
    [GCC 4.9.2 20141224 (prerelease)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import posixpath
    >>> posixpath.__file__
    '/usr/lib/python3.4/posixpath.py'

**Comment by philtay** [comment]
This is what I get:

```python
import posixpath
import time
```

```
./foo.py:1:1: F401 'posixpath' imported but unused
./foo.py:2:1: F401 'time' imported but unused
./foo.py:2:1: I100 Imports statements are in the wrong order. import time should be before import posixpath
./foo.py:2:1: I201 Missing newline before sections or imports.
```

**Comment by untitaker** [comment]
Ah, sorry, I misread your bugreport. My original impression was that *you* don't consider posixpath to be a stdlib module.

**Comment by philtay** [comment]
No prob :)
