### ISSUE TITLE
Provide changelog for library releases

### ISSUE THREAD

**Issue by playpauseandstop** [public/flake8-import-order#36]
I'm not able to find any changelog for the new 0.6 release of ``flake8-import-order`` and I honestly don't know if I safe to update it in my projects from 0.5.3

Can you provide changelog somewhere (in README or CHANGES) to be able track changes between releases?

[Here a good writing on why users needs changelogs](http://keepachangelog.com/)

Thanks

**Comment by public** [comment]
This is definitely something I should do :)

**Comment by public** [comment]
There is now a changelog file.

**Comment by playpauseandstop** [comment]
Thanks!
