### ISSUE TITLE
Does import order consider case?

### ISSUE THREAD

**Issue by mauricioabreu** [public/flake8-import-order#40]
Example:

```Imported names are in the wrong order. Should be RequestContext, get_object_or_404, render, render_to_response```

It looks like RequestContext should be in the first position because it is upper case. Am I right?
If yes I can update cryptography example and add a line considering case sensitive imports. 

Thanks! (sorry for using issues to make a question)

**Comment by public** [comment]
Yeah it does count case. It uses plain lexical order with no locale magic so upper-case comes first.

I should probably make sure the tests cover this case too :)

**Comment by mauricioabreu** [comment]
I am curious: do you like this behavior?
Don't get me wrong. I am just trying to understand your opinion.

Thanks for this library! :-)

**Comment by untitaker** [comment]
I like this behavior because it separates classes from functions during imports.
