### ISSUE TITLE
import typing not considered part of standard library

### ISSUE THREAD

**Issue by Korijn** [public/flake8-import-order#66]
The `typing` module that is part of the standard library as of Python 3.5 is not recognized as being part of the standard library: flake8-import-order is indicating that it belongs to the 3rd party module groups, under google import styling.

**Comment by pgjones** [comment]
This has been fixed in master, e59ca76002dabfac9d70170b01d78cc5b98759ab and will be part of the next release. I'll leave this open for others to reference until the release.

**Comment by Korijn** [comment]
Awesome, thanks for the info.

**Comment by pgjones** [comment]
Released now.
